/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AliveRouterView: typeof import('./src/components/alive-router-view.vue')['default']
    FootAnimation: typeof import('./src/components/foot-animation.vue')['default']
    InputSlider: typeof import('./src/components/input-slider.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UploadFile: typeof import('./src/components/upload-file.vue')['default']
  }
}
