/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AliveRouterView: typeof import('./src/components/alive-router-view.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElInput: typeof import('element-plus/es')['ElInput']
    FootAnimation: typeof import('./src/components/foot-animation.vue')['default']
    InputSlider: typeof import('./src/components/input-slider.vue')['default']
    NotFound: typeof import('./src/components/not-found.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UploadF: typeof import('./src/components/upload-f.vue')['default']
    UploadFile: typeof import('./src/components/upload-file.vue')['default']
  }
}
